services:
  - type: web
    name: tiktok-live-panel
    env: docker
    repo: https://github.com/zidanebarkat/fbwho-tools
    dockerfilePath: ./idea/tiktok-live/Dockerfile
    envVars:
      - key: PANEL_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: "0"
